#!/usr/bin/env python3
"""
The whole Mixed-ML vs Full-ML question in one number.

For each gas molecule:      delta = E_gas^MLIP - E_gas^DFT

That delta IS the error you eat when you let the MLIP predict the gas term
instead of DFT. You do not have to guess whether Full-ML is safe - measure it.

  |delta| < ~0.10 eV  ->  Full-ML is fine, skip the DFT gas reference
  |delta| ~ 0.2-0.5 eV ->  use Mixed-ML (DFT gas), or subtract delta as a
                           per-species constant correction
  |delta| > ~0.5 eV   ->  Mixed-ML, and check your functional actually matches
                           the model's training set

Run AFTER the DFT gas jobs finish:
    python gas_offset_diagnostic.py
"""
import os
import numpy as np
from ase.io import read

GASDIR = "gas_references"

# ---------------------------------------------------------------------------
# 1. Pick the calculator. IMPORTANT: the model's training functional decides
#    which DFT settings your reference must use.
#
#    MP / PBE(+U) scale  -> MACE-MP-0, MACE-MPA, CHGNet, SevenNet-0, Orb,
#                           eSEN-MPtrj/OMat24, UMA task="omat"
#    RPBE, no +U         -> anything OC20/OC22 trained, UMA task="oc20"
#
#    The inputs generated by make_gas_refs.py are the MP/PBE branch.
# ---------------------------------------------------------------------------
def get_calculator():
    from mace.calculators import mace_mp
    return mace_mp(model="medium-mpa-0", default_dtype="float64", device="cpu")

    # --- UMA alternative (note the task string must match your DFT settings) ---
    # from fairchem.core import pretrained_mlip, FAIRChemCalculator
    # predictor = pretrained_mlip.get_predict_unit("uma-s-1p1", device="cpu")
    # return FAIRChemCalculator(predictor, task_name="omat")


def read_dft_energy(folder):
    """Final total energy from a completed VASP run (OUTCAR or vasprun.xml)."""
    for fname in ("OUTCAR", "vasprun.xml"):
        path = os.path.join(folder, fname)
        if os.path.exists(path):
            try:
                return read(path, index=-1).get_potential_energy()
            except Exception:
                continue
    return None


def main():
    calc = get_calculator()
    print(f"{'species':8} {'E_DFT (eV)':>13} {'E_MLIP (eV)':>13} {'delta (eV)':>12}")
    print("-" * 50)

    deltas = {}
    for name in sorted(os.listdir(GASDIR)):
        folder = os.path.join(GASDIR, name)
        if not os.path.isdir(folder):
            continue

        e_dft = read_dft_energy(folder)
        if e_dft is None:
            print(f"{name:8} {'-- not run --':>13}")
            continue

        # Evaluate the MLIP on the SAME (DFT-relaxed) geometry.
        # Relaxing separately in the MLIP adds a second, different error.
        atoms = read(os.path.join(folder, "OUTCAR"), index=-1)
        atoms.calc = calc
        e_ml = atoms.get_potential_energy()

        d = e_ml - e_dft
        deltas[name] = d
        print(f"{name:8} {e_dft:13.4f} {e_ml:13.4f} {d:12.4f}")

    if deltas:
        v = np.array(list(deltas.values()))
        print("-" * 50)
        print(f"mean |delta| = {np.abs(v).mean():.3f} eV     "
              f"spread = {v.max() - v.min():.3f} eV")
        print("\nA large MEAN with a small SPREAD is a constant offset - correctable.")
        print("A large SPREAD means the model is species-dependent - use Mixed-ML.")

        np.save("gas_deltas.npy", deltas)
        print("\nSaved per-species deltas to gas_deltas.npy")


if __name__ == "__main__":
    main()
